project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurants.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurants/urls.py
from django.urls import path

from . import views
from .views import RestaurantCreateView

app_name = 'restaurants'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('restaurants/', views.home, name='home'),
    path('restaurants/add/', RestaurantCreateView.as_view(), name='add'),
]

restaurants/models.py
from django.db import models

from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name
    
class State(models.Model):
    name = models.CharField(max_length=65)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}, {self.country.name}"

class City(models.Model):
    name = models.CharField(max_length=65)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}, {self.state.name}"
    
class Neighborhood(models.Model):
    name = models.CharField(max_length=65)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}, {self.city.name}"
    
class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Restaurant(models.Model):
    title = models.CharField(max_length=65)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.SET_NULL, null=True)    
    description = models.CharField(max_length=255)
    opening_hours = models.TimeField()
    closing_hours = models.TimeField()
    img_restaurant = models.ImageField(upload_to='restaurant/cover/img', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.title
    
    

restaurants/forms.py
from django import forms
from .models import Restaurant, Country, City, Neighborhood, Category, State
from utils.form_widget import MultipleSelect2Widget, Select2Widget

class RestaurantForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(RestaurantForm, self).__init__(*args, **kwargs)
        
        self.fields['title'] = forms.CharField(
            widget=forms.TextInput(attrs={'class': 'form-control'}),
            required=True
        )
        self.fields['country'] = forms.ModelChoiceField(
            queryset=Country.objects.all(),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=True
        )
        self.fields['state'] = forms.ModelChoiceField(
            queryset=State.objects.all(),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=True
        )
        self.fields['city'] = forms.ModelChoiceField(
            queryset=City.objects.all(),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=True
        )
        self.fields['neighborhood'] = forms.ModelChoiceField(
            queryset=Neighborhood.objects.all(),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=True
        )
        self.fields['description'] = forms.CharField(
            widget=forms.Textarea(attrs={'class': 'form-control'}),
            required=True
        )
        self.fields['opening_hours'] = forms.TimeField(
            widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            required=True
        )
        self.fields['closing_hours'] = forms.TimeField(
            widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            required=True
        )
        self.fields['img_restaurant'] = forms.ImageField(
            widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            required=False
        )
        self.fields['category'] = forms.ModelChoiceField(
            queryset=Category.objects.all(),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=True
        )
        
        if 'instance' in kwargs and kwargs['instance']:
            instance = kwargs['instance']
            if instance.country:
                self.fields['state'].queryset = State.objects.filter(country=instance.country)
            if instance.state:
                self.fields['city'].queryset = City.objects.filter(state=instance.state)
            if instance.city:
                self.fields['neighborhood'].queryset = Neighborhood.objects.filter(city=instance.city)
        
    class Meta:
        model = Restaurant
        fields = '__all__'

restaurants/views.py
import os
from django.http import JsonResponse

from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404

from .models import *
from .forms import RestaurantForm

def dashboard(request):
    return render(request, 'restaurants/pages/dashboard.html')

def restaurant(request, id):
    return render(request, 'restaurants/pages/restaurants-view.html', context={
        'restaurant': get_object_or_404(Restaurant, id=id),
     })

def home(request):
    restaurants = Restaurant.objects.all().order_by('-id')

    return render(request, 'restaurants/pages/home.html', context={
        'restaurants': restaurants,  
    })

class RestaurantCreateView(CreateView):
    model = Restaurant
    form_class = RestaurantForm
    template_name = 'restaurants/pages/add.html'
    success_url = reverse_lazy('restaurants:home')
    
    def form_valid(self, form):
        print("Form is valid")
        form.save()
        return redirect(self.success_url)
    
    def form_invalid(self, form):
        print("Form is invalid")
        print(form.errors)
        return self.render_to_response(self.get_context_data(form=form))
    
    def get_success_url(self):
        return self.success_url

restaurants/templates/restaurants/pages/add.html
{% extends 'global/index.html' %}

{% block title%} Cadastrar Restaurante | {% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        <h1>Cadastrar Restaurante</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.title.label_tag }}
                {{ form.title }}
            </div>
            <div class="form-group">
                {{ form.country.label_tag }}
                {{ form.country }}
            </div>
            <div class="form-group">
                {{ form.state.label_tag }}
                {{ form.state }}
            </div>
            <div class="form-group">
                {{ form.city.label_tag }}
                {{ form.city }}
            </div>
            <div class="form-group">
                {{ form.neighborhood.label_tag }}
                {{ form.neighborhood }}
            </div>
            <div class="form-group">
                {{ form.description.label_tag }}
                {{ form.description }}
            </div>
            <div class="form-group">
                {{ form.opening_hours.label_tag }}
                {{ form.opening_hours }}
            </div>
            <div class="form-group">
                {{ form.closing_hours.label_tag }}
                {{ form.closing_hours }}
            </div>
            <div class="form-group">
                {{ form.img_restaurant.label_tag }}
                {{ form.img_restaurant }}
            </div>
            <div class="form-group">
                {{ form.category.label_tag }}
                {{ form.category }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock content %}

restaurants/templates/restaurants/pages/dashboard.html
{% extends "global/index.html" %}

{% block title %}Home | {% endblock title %}
{% block content %}
    <div class="main-content-button container">
        <button class="outline1">
            <a href="{% url 'restaurants:add' %}">Cadastrar Restaurante</a>
        </button>
        <button class="outline2">
            <a href="{% url 'restaurants:home' %}">Listar Restaurantes</a>
        </button>
    </div>

{% endblock content %}

restaurants/templates/restaurants/pages/home.html
{% extends "global/index.html" %}

{% block title %}Restaurantes | {% endblock title %}
{% block content %}
    <div class="main-content main-content-list container">
        {% for restaurant in restaurants %}
            {% include 'restaurants/partials/restaurant.html' %}
        {% empty %}
                <div class="center m-y">
                    <h1>Não há nenhum restaurante cadastrado!</h1>
                </div>
        {% endfor %}
    </div>
{% endblock content %}

restaurants/templates/restaurants/pages/restaurants-view.html
{% extends 'global/index.html' %}

{% block title %}{{ restaurant.title }} | {% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'restaurants/partials/restaurant.html' %}
    </div>
{% endblock content %}

restaurants/templates/restaurants/partials/restaurant.html
<div class="restaurant restaurant-list-item">
    {% if restaurant.img_restaurant %}
        <div class="restaurant-cover">
            <img src="{{ restaurant.img_restaurant.url }}" alt="{{ restaurant.title }}">
        </div>
    {% endif %}
    <div class="restaurant-title-container">
        <h2 class="restaurant-title">
            {{ restaurant.title }}
        </h2>
    </div>
    <div class="restaurant-container">
        <span class="restaurant-type-item">
            <i class="fas fa-layer-group type-item"></i>
            <span>{{ restaurant.category.name }}</span>
        </span>
    </div>
    <div class="restaurant-meta-container">
        <div class="restaurant-content">
            <p>
                {{ restaurant.description }}
            </p>
        </div>
        <div class="restaurant-time">
            <span class="restaurant-time-item">
                <h3 class="restaurant-time-title"><i class="fas fa-stopwatch"></i> Horário de funcionamento:
                    <i>{{ restaurant.opening_hours|date:"H:i" }} às {{ restaurant.closing_hours|date:"H:i" }}</i>
                </h3>
            </span>
        </div>
    </div>
</div>